worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        location / {
            proxy_set_header NewHeader "New";
            proxy_pass http://localhost:1234;
        }
    }
}
