[package]
name = "test-helpers"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
http-body-util = {workspace=true}
anyhow = "1.0.98"
hyper = { version = "1.5.2", features = ["server", "http1"] }
hyper-util = {workspace=true, features = ["tokio"]}
bytes = {workspace=true}
serde = {workspace=true, features = ["derive"]}
tokio = {workspace=true, features = ["rt", "rt-multi-thread", "net", "macros", "io-util"]}
serde_json = {workspace=true}
httparse = "1.10.1"

[dev-dependencies]
hyper = { version = "1.5.2", features = ["client"] }
