/*
 * This source file was generated by the Gradle 'init' task
 */
package main

import kotlin.test.Test
import kotlinx.coroutines.runBlocking

class OoniProbeClientTest {
    @Test
    fun getRequestWorks() = runBlocking {
        val client =
                OoniProbeClient.Builder()
                        .setOptions(ClientOptions("https://api.ooni.org/", 10, "ooniprobe"))
                        .build()
        val res = client.get("/api/v2/oonirun/links/10001/engine-descriptor/1")
        print(res)
    }
}
