/*
 * This source file was generated by the Gradle 'init' task
 */
package main

import kotlin.test.*
import kotlin.test.Test
import kotlinx.coroutines.runBlocking

class OoniProbeClientTest {
    @Test
    fun getRequestWorks() = runBlocking {
        val client =
                OoniProbeClient.Builder()
                        .setOptions(ClientOptions("https://api.ooni.org/", 10, "ooniprobe"))
                        .build()
        val res = client.get("/api/v2/oonirun/links/10001/engine-descriptor/1")
        assertEquals(res.status_code, 200)
        assertTrue(res.body_text!!.length > 0)
    }
    @Test
    fun getRequestBuilderWorks() = runBlocking {
        val client =
                OoniProbeClient.Builder()
                        .setOptions(ClientOptions("https://api.ooni.org/", 10, "ooniprobe"))
                        .build()
        val request = client.request("GET", "https://example.com")
        val res = request.send()
        assertEquals(res.status_code, 200)
        assertTrue(res.body_text!!.length > 0)
    }
}
